version: "3.8"

services:
  redis:
    image: redis
    ports:
    - 6379:6379

  builder:
    build:
      context: .
      dockerfile: build.Dockerfile
    volumes:
      - ./:/build/
      - ./build_target:/build/target

  release:
    image: registry.gitlab.com/awfrke/unexpected_cats
    build:
      context: .
      dockerfile: release.Dockerfile
    environment:
      REDIS_HOST: redis
      REDIS_DB: 11
